org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

# Forge
forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=endfield_spellbook
mod_name=Endfield Spellbook
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.zzdzt.endfield_spellbook
mod_authors=wistaria
mod_description=终末地风格铁魔法附属
mod_url=https://github.com/zzdzt/endfield_spellbook

# Dependencies

tacz_version=0
tacz_version_cf_id=0

irons_spellbooks_version=1.20.1-3.16.2
irons_spellbooks_version_cf_id=8364933

irons_lib_version=1.20.1-2.1.0
irons_lib_version_cf_id=8364892

curios_version=5.14.1+1.20.1
curios_version_cf_id=6418456

jei_version=15.20.0.108